#Clemens' Blog

theme: jekyll-theme-minimal

title: "Clemens Zauchner"
description: "Clemens' Blog"



# author
author:
  first_name: 'Clemens'
  last_name: 'Zauchner'
  email: 'cst.zauchner@gmail.com'
  linkedin_username: 'clemenszauchner'
  stackoverflow_username: '8745763/clemens'
  github_username: 'clemens-zauchner'
  head_img: ''
  desc: 'Lorem ipsum'


# markdown
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

